env:
  source_branch: main

name: pages

# push and pull requests are made to the 'main' branch
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js (and yarn, I think)
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12.x'
    # https://github.com/actions/cache/blob/master/examples.md#node---yarn
    - name: Find out name of yarn cache path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Cache yarn
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    # actual stuff starts here
    - name: Install dependencies using yarn
      run: yarn install
    - name: Build project using yarn
      run: yarn build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

  deploy:
    # build before deploy
    needs: build
    runs-on: ubuntu-latest
    # only run deploy if trigger is source branch
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Get artifacts from build
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: public
      - name: Publish to Github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: public
          cname: perzeption.github.io
          enable_jekyll: false